example/app/pubspec.lock, example/app/pubspec.yaml, melos.yaml
Introduce melos to manage packages.
https://pub.dev/packages/melos
```
dart pub global activate melos
```
```
melos bootstrap
```
```
melso run
```
=> chore: introduce melos to manage packages

playbook_snapshot/lib/src/snapshot.dart
=> feat: use `/` between story and scenario

example/app/lib/bar/bar.story.dart, example/app/lib/generated_playbook.dart, playbook_generator/lib/src/playbook_builder.dart
Support:
```dart
List<Scenario> multipleScenarios() => ...
```
=> feat: support generate code from return type of list scenario

example/app/lib/foo/foo_widget.story.dart, example/app/lib/generated_playbook.dart, example/app/pubspec.lock, example/app/pubspec.yaml, playbook/lib/playbook.dart, playbook/lib/playbook_annotations.dart, playbook/lib/src/generate_scenario.dart, playbook/pubspec.lock, playbook_generator/lib/src/constant_reader_utils.dart, playbook_generator/lib/src/playbook_builder.dart, playbook_generator/pubspec.lock, playbook_generator/pubspec.yaml, playbook_snapshot/pubspec.lock, playbook_ui/lib/src/playbook_gallery.dart, playbook_ui/lib/src/scenario_container.dart, playbook_ui/pubspec.lock
- GenerateScenario annotation
- Generate scenario from widget class
- PlaybookGallery update stories when widget change
- Sort story and scenario via title
- Unfocus search after navigation
=> GenerateScenario, Gallery Hot Reload, Sort

playbook_ui/lib/src/playbook_gallery.dart
- specify key for scenario
- sometime error when using hooks in scenario
=> feat: key for scenario

playbook_ui/lib/src/scenario_container.dart
=> fix: hot reload error

analysis_options.yaml, example/app/lib/foo/foo_widget.story.dart, example/app/lib/generated_playbook.dart, example/app/pubspec.lock, example/catalog_app/pubspec.lock, playbook/pubspec.lock, playbook/pubspec.yaml, playbook_generator/pubspec.lock, playbook_generator/pubspec.yaml, playbook_snapshot/pubspec.lock, playbook_snapshot/pubspec.yaml, playbook_ui/pubspec.lock, playbook_ui/pubspec.yaml, pubspec.lock
- flutter 2.5.0
- analyzer 2.0.0
- dart/flutter lints
=> build: flutter 2.5.0, analyzer 2.0.0, new lints

playbook_snapshot/lib/src/snapshot.dart, playbook_snapshot/lib/src/test_tool.dart
=> feat: add custom set up hook

example/app/lib/foo/foo_widget.story.dart, example/app/lib/generated_playbook.dart, melos.yaml, playbook_generator/lib/src/constant_reader_utils.dart
=> fix generator to handle named parameters

examples/component_example/component_catalog_app/pubspec.lock, examples/generator_example/generator_app/pubspec.lock, playbook_generator/pubspec.lock, playbook_generator/pubspec.yaml
https://github.com/leisim/dartx
=> build: bump dartx 0.8.0

examples/component_example/component_catalog_app/pubspec.lock, examples/generator_example/generator_app/lib/generated_playbook.dart, examples/generator_example/generator_app/pubspec.lock, examples/generator_example/generator_catalog_app/pubspec.lock, examples/simple_example/simple_app/pubspec.lock, examples/simple_example/simple_catalog_app/pubspec.lock, melos.yaml, playbook_generator/lib/src/playbook_builder.dart, playbook_generator/pubspec.lock, playbook_snapshot/pubspec.lock, playbook_ui/pubspec.lock
- upgrade generator dependencies (e.g. analyzer 2.8.0) and fix error
- use `melos bootstrap`
=> build: upgrade generator dependencies

examples/component_example/component_catalog_app/pubspec.lock, examples/generator_example/generator_app/pubspec.lock, examples/generator_example/generator_catalog_app/pubspec.lock, examples/simple_example/simple_app/pubspec.lock, examples/simple_example/simple_catalog_app/pubspec.lock, playbook/CHANGELOG.md, playbook/pubspec.yaml, playbook_generator/CHANGELOG.md, playbook_generator/pubspec.lock, playbook_generator/pubspec.yaml, playbook_snapshot/CHANGELOG.md, playbook_snapshot/pubspec.lock, playbook_snapshot/pubspec.yaml, playbook_ui/CHANGELOG.md, playbook_ui/pubspec.lock, playbook_ui/pubspec.yaml
`melos version && melos publish --no-dry-run`
- playbook@0.0.2
- playbook_generator@0.0.2
- playbook_snapshot@0.0.2
- playbook_ui@0.0.2
=> chore(release): publish packages 0.0.2

examples/component_example/component_catalog_app/pubspec.lock, examples/generator_example/generator_app/pubspec.lock, playbook_generator/lib/src/playbook_builder.dart, playbook_generator/pubspec.lock, playbook_generator/pubspec.yaml
There is no need to using dartx
=> feat: remove dartx and use dart api

examples/component_example/component_catalog_app/pubspec.lock, examples/generator_example/generator_catalog_app/pubspec.lock, examples/simple_example/simple_catalog_app/pubspec.lock, playbook_ui/lib/src/component/story_drawer.dart, playbook_ui/lib/src/playbook_gallery.dart, playbook_ui/pubspec.lock, playbook_ui/pubspec.yaml
scroll_to_index works badly with large amount stories.
Simply set the story title to TextController.
=> fix: set story title to TextController when click drawer item

examples/component_example/component_catalog_app/test/snapshot_test.dart, examples/generator_example/generator_catalog_app/test/snapshot_test.dart, examples/simple_example/simple_catalog_app/test/snapshot_test.dart, playbook_snapshot/lib/src/font_builder.dart, playbook_snapshot/lib/src/snapshot.dart, playbook_snapshot/lib/src/snapshot_support.dart, playbook_snapshot/lib/src/test_tool.dart, playbook_ui/lib/src/playbook_gallery.dart
`testWidgets` can be called only once.
=> Fix snapshot

examples/component_example/component_app/android/app/build.gradle, examples/component_example/component_app/android/build.gradle, examples/component_example/component_catalog_app/android/app/build.gradle, examples/component_example/component_catalog_app/android/app/src/main/AndroidManifest.xml, examples/component_example/component_catalog_app/android/build.gradle, examples/generator_example/generator_app/android/app/src/main/AndroidManifest.xml, examples/generator_example/generator_app/android/build.gradle, examples/generator_example/generator_catalog_app/android/app/build.gradle, examples/generator_example/generator_catalog_app/android/app/src/main/AndroidManifest.xml, examples/generator_example/generator_catalog_app/android/build.gradle, examples/simple_example/simple_app/android/app/build.gradle, examples/simple_example/simple_app/android/app/src/main/AndroidManifest.xml, examples/simple_example/simple_app/android/build.gradle, examples/simple_example/simple_catalog_app/android/app/build.gradle, examples/simple_example/simple_catalog_app/android/app/src/main/AndroidManifest.xml, examples/simple_example/simple_catalog_app/android/build.gradle
=> fix: android example build

playbook_ui/lib/src/playbook_gallery.dart
Rework of #52 to manage lifecycle and updating TextEditingController correctly
=> feat: expose searchTextController

examples/component_example/component_catalog_app/lib/generated_playbook.dart, examples/generator_example/generator_app/lib/generated_playbook.dart, playbook/lib/src/generate_scenario.dart, playbook/lib/src/scenario.dart, playbook_generator/lib/src/playbook_builder.dart, playbook_ui/lib/src/playbook_gallery.dart, playbook_ui/lib/src/scenario_container.dart
- Setting different scenario thumbnail scales seems not very useful
- Controlling the overall scale in PlaybookGallery should be more convenient
=> feat: set scenario thumbnail scale from PlaybookGallery

examples/simple_example/simple_catalog_app/lib/main.dart, playbook_ui/lib/src/playbook_gallery.dart
widget.searchTextController should initialize with adding listener
=> fix: add listener to text controller

playbook_ui/lib/src/component/component.dart, playbook_ui/lib/src/component/search_box.dart, playbook_ui/lib/src/component/story_drawer.dart, playbook_ui/lib/src/playbook_gallery.dart
close #61 
SearchBar has been added since flutter 3.10.0.
We have renamed it to SearchBox as a work around.
=> Rename SearchBar to SearchBox

playbook/lib/src/scenario_layout.dart, playbook_snapshot/lib/src/snapshot_support.dart
use `ScenarioLayoutFill` instead.
=> fix: remove needsScrollableResizing arg

examples/generator_app/lib/generated_playbook.dart, melos.yaml, packages/playbook_generator/lib/src/playbook_builder.dart, packages/playbook_generator/pubspec.yaml
update analyzer to greater than 7.4.5
=> chore: update analyzer

README.md, packages/playbook/CHANGELOG.md, packages/playbook/pubspec.yaml, packages/playbook_generator/CHANGELOG.md, packages/playbook_generator/pubspec.yaml, packages/playbook_snapshot/CHANGELOG.md, packages/playbook_snapshot/pubspec.yaml, packages/playbook_ui/CHANGELOG.md, packages/playbook_ui/pubspec.yaml
This PR prepares the release of version 1.3.0 for all packages, updating CHANGELOGs and package versions to reflect the changes made since v1.2.0.
- Updated CHANGELOG.md for all packages (playbook, playbook_generator, playbook_snapshot, playbook_ui) to include v1.3.0 release notes
- Bumped package versions from 1.2.0 to 1.3.0 in all pubspec.yaml files
- Updated README.md requirements section to reflect minimum Dart 3.9.0+ and Flutter 3.35.0+
- **SDK Updates**: Dart constraint updated to `^3.9.0`, Flutter constraint to `>=3.35.0`
- **Analysis**: Migrated to `very_good_analysis` 10.0.0
- **Infrastructure**: Migrated from Melos workspace to Dart workspace configuration
- **CI/CD**: Migrated from `subosito/flutter-action` to `jdx/mise-action`
- **Version Management**: Added `.mise.toml` for …
=> chore: release version 1.3.0
